LD_BIND_NOW=1
LV2_PATH=/root/.lv2:/usr/lib/lv2:/mnt/plugins
MOD_DEFAULT_PEDALBOARD=/mnt/pedalboards/default.pedalboard
MOD_DEV_HMI=1
MOD_FACTORY_PEDALBOARDS_DIR=/mnt/pedalboards
MOD_KEYS_PATH=/root/keys/
MOD_MODEL_CPU=x86_64
MOD_MODEL_TYPE=live-usb:x86_64
SNDFILE_JACKPLAY_AUTOCONNECT=mod-host:monitor-in_%d

MOD_DEVICE_WEBSERVER_PORT=8888
MOD_FILE_MANAGER_PORT=8081
MOD_HOST_SOCKET_PORT=5555
