
# list of known good projects
PROJECTS += abgate
PROJECTS += amsynth
PROJECTS += artyfx
PROJECTS += bolliedelay
# PROJECTS += calf
PROJECTS += caps-lv2
PROJECTS += carla-plugins
PROJECTS += die-plugins
# PROJECTS += distrho-ports
PROJECTS += dpf-plugins
PROJECTS += fluidplug
PROJECTS += fomp
PROJECTS += freaked
PROJECTS += guitarix
PROJECTS += gxbajatubedriver
PROJECTS += gxbottlerocket
PROJECTS += gxguvnor
PROJECTS += gxhotbox
PROJECTS += gxhyperion
PROJECTS += gxknightfuzz
PROJECTS += gxquack
PROJECTS += gxsaturate
PROJECTS += gxsd1
PROJECTS += gxsd2lead
PROJECTS += gxsfp
PROJECTS += gxslowgear
PROJECTS += gxsupersonic
PROJECTS += gxsvt
PROJECTS += gxswitchlesswah
PROJECTS += gxtimray
PROJECTS += gxtonemachine
PROJECTS += gxuvox
PROJECTS += gxvbass
PROJECTS += gxvintagefuzzmaster
PROJECTS += gxvmk2d
PROJECTS += gxvoodoo
PROJECTS += gxvoxtb
PROJECTS += gxvstb
PROJECTS += infamous-plugins
PROJECTS += invada-lv2
PROJECTS += mod-cv-plugins
# PROJECTS += lsp-plugins-impulsantworten
PROJECTS += lv2-examples
PROJECTS += mod-ams-lv2
PROJECTS += mod-arpeggiator
PROJECTS += mod-audio-mixers
# PROJECTS += mod-audio-to-cv-pitch
PROJECTS += mod-cabsim-ir-loader
PROJECTS += mod-cv-plugins
PROJECTS += mod-distortion
PROJECTS += mod-mda-lv2
PROJECTS += mod-midi-utilities
PROJECTS += mod-pitchshifter
PROJECTS += mod-tal-noisemaker
PROJECTS += mod-utilities
PROJECTS += mod-volume
PROJECTS += notes-lv2
PROJECTS += remaincalm-plugins
PROJECTS += rkrlv2
# PROJECTS += samplv1
PROJECTS += setbfree-mod
PROJECTS += setbfree
PROJECTS += shiro-plugins
PROJECTS += sooperlooper-lv2
PROJECTS += tal-reverb
PROJECTS += tap-lv2
PROJECTS += x42-fat1
PROJECTS += x42-fil4
PROJECTS += x42-mclk
PROJECTS += x42-midifilter
PROJECTS += x42-midigen
PROJECTS += x42-mtc
PROJECTS += x42-stepseq
PROJECTS += x42-tinygain
PROJECTS += x42-xfade
PROJECTS += zam-plugins
# not in stable/prod, but still useful for many reasons
PROJECTS += modmeter
PROJECTS += modspectre-labs
PROJECTS += x42-tuna-lv2-labs


# list of known good bundles
BUNDLES += abGate.lv2
BUNDLES += amsynth.lv2
BUNDLES += artyfx.lv2
BUNDLES += bolliedelay.lv2
# BUNDLES += calf.lv2
BUNDLES += mod-caps-AmpVTS.lv2 mod-caps-AutoFilter.lv2 mod-caps-CabinetIV.lv2 mod-caps-CEO.lv2 mod-caps-Click.lv2 mod-caps-PhaserII.lv2 mod-caps-Plate.lv2 mod-caps-PlateX2.lv2 mod-caps-Scape.lv2 mod-caps-Spice.lv2 mod-caps-SpiceX2.lv2 mod-caps-White.lv2 mod-caps-Wider.lv2
BUNDLES += carla-files.lv2
BUNDLES += distrho-a-fluidsynth.lv2
# BUNDLES += Vex.lv2
BUNDLES += Kars.lv2 MVerb.lv2 Nekobi.lv2 PingPongPan.lv2
BUNDLES += Black_Pearl_4A.lv2 Black_Pearl_4B.lv2 Black_Pearl_5.lv2 FluidBass.lv2 FluidBrass.lv2 FluidChromPerc.lv2 FluidDrums.lv2 FluidEnsemble.lv2 FluidEthnic.lv2 FluidGuitars.lv2 FluidOrgans.lv2 FluidPercussion.lv2 FluidPianos.lv2 FluidPipes.lv2 FluidReeds.lv2 FluidSoundFX.lv2 FluidStrings.lv2 FluidSynthFX.lv2 FluidSynthLeads.lv2 FluidSynthPads.lv2 Red_Zeppelin_4.lv2 Red_Zeppelin_5.lv2", "stable": true }
BUNDLES += fomp.lv2
BUNDLES += Freakclip.lv2 Freaktail.lv2 Prefreak.lv2 Granulator.lv2
BUNDLES += gx_amp.lv2 gx_amp_stereo.lv2 gx_cabinet.lv2 gx_colwah.lv2 gx_compressor.lv2 gx_cstb.lv2 gx_delay.lv2 gx_detune.lv2 gx_digital_delay.lv2 gx_digital_delay_st.lv2 gx_duck_delay.lv2 gx_duck_delay_st.lv2 gx_echo.lv2 gx_expander.lv2 gx_flanger.lv2 gx_fumaster.lv2 gx_fuzz.lv2 gx_fuzzface.lv2 gx_fuzzfacefm.lv2 gx_gcb_95.lv2 gx_hfb.lv2 gx_hogsfoot.lv2 gx_hornet.lv2 gx_jcm800pre.lv2 gx_jcm800pre_st.lv2 gx_mbdelay.lv2 gx_mole.lv2 gx_muff.lv2 gx_oc_2.lv2 gx_phaser.lv2 gx_rangem.lv2 gx_redeye.lv2 gx_reverb.lv2 gx_room_simulator.lv2 gx_scream.lv2 gx_shimmizita.lv2 gx_studiopre.lv2 gx_studiopre_st.lv2 gx_susta.lv2 gx_switched_tremolo.lv2 gxbooster.lv2 gxtilttone.lv2 gxts9.lv2 gxwah.lv2
BUNDLES += gx_bajatubedriver.lv2
BUNDLES += gx_bottlerocket.lv2
BUNDLES += gx_guvnor.lv2
BUNDLES += gx_hotbox.lv2
BUNDLES += gx_hyperion.lv2
BUNDLES += gx_KnightFuzz.lv2
BUNDLES += gx_quack.lv2
BUNDLES += gx_saturate.lv2
BUNDLES += gx_sd1sim.lv2
BUNDLES += gx_sd2lead.lv2
BUNDLES += gx_sfp.lv2
BUNDLES += gx_slowgear.lv2
BUNDLES += gx_supersonic.lv2
BUNDLES += gx_ampegsvt.lv2
BUNDLES += GxSwitchlessWah.lv2
BUNDLES += gx_timray.lv2
BUNDLES += gx_tonemachine.lv2
BUNDLES += gx_uvox.lv2
BUNDLES += gx_voxbass.lv2
BUNDLES += gx_vfm.lv2
BUNDLES += gx_vmk2d.lv2
BUNDLES += gx_voodoo.lv2
BUNDLES += gx_voxtb.lv2
BUNDLES += gx_vstb.lv2
BUNDLES += powercut.lv2 stuck.lv2 hip2b.lv2 mindi.lv2
BUNDLES += invada.lv2
BUNDLES += logic-operators.lv2
# BUNDLES += lsp-plugins-impulsantworten.lv2
BUNDLES += eg-metro.lv2 eg-sampler.lv2
BUNDLES += mod-ams.lv2
BUNDLES += mod-arpeggiator.lv2
BUNDLES += mod-mixer.lv2 mod-mixer-stereo.lv2
# BUNDLES += mod-audio-to-cv-pitch.lv2
BUNDLES += cabsim-IR-loader.lv2
BUNDLES += mod-audio-to-cv.lv2 mod-cv-attenuverter.lv2 mod-cv-clock.lv2 mod-cv-control.lv2 mod-cv-switch1.lv2 mod-cv-switch2.lv2 mod-cv-switch3.lv2 mod-cv-switch4.lv2 mod-midi-to-cv-mono.lv2 mod-midi-to-cv-poly.lv2 mod-cv-meter.lv2 mod-cv-parameter-modulation.lv2 mod-cv-slew.lv2 mod-cv-range.lv2 mod-cv-random.lv2 mod-cv-abs.lv2 mod-cv-round.lv2 mod-cv-gate.lv2
BUNDLES += mod-bigmuff.lv2 mod-ds1.lv2
BUNDLES += mod-mda-Ambience.lv2 mod-mda-BeatBox.lv2 mod-mda-Detune.lv2 mod-mda-DubDelay.lv2 mod-mda-DX10.lv2 mod-mda-EPiano.lv2 mod-mda-JX10.lv2 mod-mda-Leslie.lv2 mod-mda-Overdrive.lv2 mod-mda-Piano.lv2 mod-mda-RePsycho.lv2 mod-mda-RingMod.lv2 mod-mda-RoundPan.lv2 mod-mda-SubSynth.lv2 mod-mda-ThruZero.lv2 mod-mda-Vocoder.lv2
BUNDLES += midi-switchbox_1-2_2C.lv2 midi-switchbox_1-2.lv2 midi-switchbox_1-3.lv2 midi-switchbox_2-1_2C.lv2 midi-switchbox_2-1.lv2 midi-switchbox_3-1.lv2
BUNDLES += mod-2voices.lv2 mod-capo.lv2 mod-drop.lv2 mod-harmonizer.lv2 mod-harmonizer2.lv2 mod-harmonizercs.lv2 mod-supercapo.lv2 mod-superwhammy.lv2
BUNDLES += TAL-NoiseMaker-ME.lv2
BUNDLES += mod-bpf.lv2 mod-bypass.lv2 mod-crossover2.lv2 mod-crossover3.lv2 mod-gain.lv2 mod-gain2x2.lv2 mod-hpf.lv2 mod-lpf.lv2 mod-switchbox2.lv2 mod-toggleswitch4.lv2 switchbox_1-2_st.lv2 switchbox_2-1.lv2 switchbox_2-1_st.lv2
BUNDLES += mod-volume.lv2 mod-volume-2x2.lv2
BUNDLES += notes.lv2
BUNDLES += avocado.lv2 floaty.lv2 mud.lv2 paranoia.lv2
BUNDLES += rkr.lv2
# BUNDLES += samplv1.lv2
BUNDLES += b_whirl_mod
BUNDLES += b_synth b_whirl
BUNDLES += Harmless.lv2 Larynx.lv2 Modulay.lv2 Shiroverb.lv2
BUNDLES += sooperlooper.lv2 sooperlooper-2x2.lv2
BUNDLES += mod-tal-Reverb-2.lv2
BUNDLES += tap-autopan.lv2 tap-chorusflanger.lv2 tap-doubler.lv2 tap-dynamics.lv2 tap-dynamics-st.lv2 tap-echo.lv2 tap-eqbw.lv2 tap-eq.lv2 tap-pinknoise.lv2 tap-reflector.lv2 tap-reverb.lv2 tap-sigmoid.lv2 tap-tremolo.lv2 tap-tubewarmth.lv2
BUNDLES += fat1.lv2
BUNDLES += fil4.lv2
BUNDLES += mclk.lv2
BUNDLES += midifilter.lv2
BUNDLES += midigen.lv2
BUNDLES += mtc.lv2
BUNDLES += stepseq_s8n4.lv2 stepseq_s8n8.lv2 stepseq_s8n16.lv2 stepseq_s16n8.lv2 stepseq_s32n8.lv2
BUNDLES += tinygain.lv2
BUNDLES += xfade.lv2
BUNDLES += ZamComp.lv2 ZamCompX2.lv2
# not in stable/prod, but still useful for many reasons
BUNDLES += modmeter.lv2
BUNDLES += modspectre.lv2
BUNDLES += tuna.lv2


# include plugin projects for version and bundle list
# TODO only import known-good projects
MAKEFILES = $(wildcard mod-plugin-builder/plugins/package/*/*.mk)
include $(MAKEFILES)

# function to convert project name into buildroot var name
BUILDROOT_VAR = $(shell echo $(1) | tr a-z A-Z | tr - _)

# function to convert project name into stamp filename
PROJECT_STAMP = .stamps/$(1)/$($(call BUILDROOT_VAR,$(1))_VERSION)

# utilities
COMMA  = ,
SPACE  =
SPACE +=

all: $(foreach PROJECT,$(PROJECTS),$(call PROJECT_STAMP,$(PROJECT))) docker/.stamp_built

define BUILD_PLUGIN
	docker run -v $(CURDIR)/bundles:/opt/mount --rm mod-live-usb_plugins:latest \
		/home/builder/build-and-copy-bundles.sh $(1) \
		$(subst $(SPACE),$(COMMA),$(filter $(BUNDLES),$($(call BUILDROOT_VAR,$(1))_BUNDLES)))
endef

.stamps/%:
	$(shell mkdir -p $(shell dirname $@))
	$(call BUILD_PLUGIN,$(firstword $(subst /, ,$*)))
	touch $@

docker/.stamp_built: docker/Dockerfile
	./docker/build.sh
	touch $@
